let lessons = [
  {
    "id": 0,
    "title": "Math",
    "location": "Germany",
    "price": 450,
    "spaces": 11,
    "img_url": "./assets/images/math-image.jpg",
  },
  {
    "id": 1,
    "title": "English",
    "location": "Germany",
    "price": 300,
    "spaces": 15,
    "img_url": "./assets/images/english-image.jpg",
  },
  {
    "id": 2,
    "title": "chemistry",
    "location": "Germany",
    "price": 400,
    "spaces": 15,
    "img_url": "./assets/images/chemistry-image.jpg",
  },
  {
    "id": 3,
    "title": "physics",
    "location": "Germany",
    "price": 250,
    "spaces": 15,
    "img_url": "./assets/images/physics-image.jpg",
  },
  {
   " id": 4,
    "title": "Language",
    "location": "Germany",
    "price": 350,
    "spaces": 15,
    "img_url": "./assets/images/language-image.jpg",
  },
  {
    "id": 5,
    "title": "Biology",
    "location": "Germany",
    "price": 250,
    "spaces": 15,
    "img_url": "./assets/images/biology-image.jpg",
  },
  {
    "id": 6,
    "title": "Art",
    "location": "Germany",
    "price": 200,
    "spaces": 15,
    "img_url": "./assets/images/art-image.jpg",
  },
  {
    "id": 7,
    "title": "Computer Science",
    "location": "Germany",
    "price": 300,
    "spaces": 15,
    "img_url": "./assets/images/computer-science-image.jpg",
  },
  {
    "id": 8,
    "title": "Psychology",
    "location": "Germany",
    "price": 500,
    "spaces": 15,
    "img_url": "./assets/images/biology-image.jpg",
  },
  {
    "id": 9,
    "title": "Law",
    "location": "Germany",
    "price": 450,
    "spaces": 15,
    "img_url": "./assets/images/law-image.jpg",
  },
];
